*msg,fatal
FATAL ERROR: VWPSLICEXZ macro has been DEPRECATED.

/eof

! VWPSLICEXZ, y,
! VWPSLICEXZ, arg1

! Descrição:
! Divide todos os volumes selecionados pelo working plane posicionado de acordo com arg1 (y).

! Lista de variáveis locais
! -

! Posicionar o working plane
WPLANE,-1,,arg1,,1,arg1,,,arg1,1

! Ocultar working plane
WPSTYL,,,,,,,,0

! Dividir áreas
VSBW,ALL,,DELETE

! Trazer o working plane de volta à posição original
WPCSYS,-1,0

! Ocultar working plane
WPSTYL,,,,,,,,0

