*msg,fatal
FATAL ERROR: WPSLICEXY macro has been DEPRECATED.

/eof

! WPSLICEXY, z,
! WPSLICEXY, arg1

! Descrição:
! Divide todas as áreas selecionadas pelo working plane posicionado de acordo com arg1 (z).

! Lista de variáveis locais
! -

! Posicionar o working plane
WPLANE,-1,,,arg1,1,,arg1,,1,arg1

! Ocultar working plane
WPSTYL,,,,,,,,0

! Dividir áreas
ASBW,ALL,SEPO,DELETE

! Trazer o working plane de volta à posição original
WPCSYS,-1,0

! Ocultar working plane
WPSTYL,,,,,,,,0
